### ISSUE TITLE
Build#83 had error installing bower but did not fail

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-image#71]
http://build.openrov.com:8080/job/OpenROV-DEBIAN-050-disk-image/83/console

-----------------------------
Customizing image
-----------------------------
------------------------------
installing bower
npm ERR! SyntaxError: Unexpected end of input
npm ERR!     at Object.parse (native)
npm ERR!     at /usr/share/npm/node_modules/uid-number/uid-number.js:38:18
npm ERR!     at ChildProcess.exithandler (child_process.js:641:7)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-29-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bower"
npm ERR! cwd /
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_eos
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0
Setting up users

**Comment by BrianAdams** [comment]
The bower install has been disabled.
The script now fails on error.

Need to validate bower is not already installed globally through another means.  Stuck on trying to install it the way we are on the script.

**Comment by BrianAdams** [comment]
Confirmed that bower is installed somewhere else. Installing the community-plugin still works which uses bower.

**Comment by BrianAdams** [comment]
Leaving out of that script for now.
